/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Alert = IDL.Record({
  'alertType' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat64,
  'severity' : IDL.Nat,
});
export const CalibrationProfile = IDL.Record({
  'lastUpdated' : IDL.Nat64,
  'mouseMovementBaseline' : IDL.Float64,
  'calibrationAccuracy' : IDL.Float64,
  'typingSpeedBaseline' : IDL.Nat32,
});
export const SessionSnapshot = IDL.Record({
  'fatigueScore' : IDL.Nat,
  'focusScore' : IDL.Nat,
  'stressScore' : IDL.Nat,
  'timestamp' : IDL.Nat64,
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'clearUserData' : IDL.Func([], [], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCalibrationProfile' : IDL.Func(
      [],
      [IDL.Opt(CalibrationProfile)],
      ['query'],
    ),
  'getSessionHistory' : IDL.Func([], [IDL.Vec(SessionSnapshot)], ['query']),
  'recordSessionSnapshot' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'saveCalibrationProfile' : IDL.Func(
      [IDL.Nat32, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Alert = IDL.Record({
    'alertType' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat64,
    'severity' : IDL.Nat,
  });
  const CalibrationProfile = IDL.Record({
    'lastUpdated' : IDL.Nat64,
    'mouseMovementBaseline' : IDL.Float64,
    'calibrationAccuracy' : IDL.Float64,
    'typingSpeedBaseline' : IDL.Nat32,
  });
  const SessionSnapshot = IDL.Record({
    'fatigueScore' : IDL.Nat,
    'focusScore' : IDL.Nat,
    'stressScore' : IDL.Nat,
    'timestamp' : IDL.Nat64,
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'clearUserData' : IDL.Func([], [], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCalibrationProfile' : IDL.Func(
        [],
        [IDL.Opt(CalibrationProfile)],
        ['query'],
      ),
    'getSessionHistory' : IDL.Func([], [IDL.Vec(SessionSnapshot)], ['query']),
    'recordSessionSnapshot' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'saveCalibrationProfile' : IDL.Func(
        [IDL.Nat32, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };