/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'alertType' : string,
  'message' : string,
  'timestamp' : bigint,
  'severity' : bigint,
}
export interface CalibrationProfile {
  'lastUpdated' : bigint,
  'mouseMovementBaseline' : number,
  'calibrationAccuracy' : number,
  'typingSpeedBaseline' : number,
}
export interface SessionSnapshot {
  'fatigueScore' : bigint,
  'focusScore' : bigint,
  'stressScore' : bigint,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'addAlert' : ActorMethod<[string, string, bigint], undefined>,
  'clearUserData' : ActorMethod<[], undefined>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getCalibrationProfile' : ActorMethod<[], [] | [CalibrationProfile]>,
  'getSessionHistory' : ActorMethod<[], Array<SessionSnapshot>>,
  'recordSessionSnapshot' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'saveCalibrationProfile' : ActorMethod<[number, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];